apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-code-server.fullname" . }}
  labels:
    {{- include "kube-code-server.labels" . | nindent 4 }}
data:
  {{ if .Values.password }}
  password: "{{ .Values.password | b64enc }}"
  {{ else }}
  password: "{{ randAlphaNum 24 | b64enc }}"
  {{ end }}
