apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "kube-code-server.fullname" . }}
  labels:
    {{- include "kube-code-server.labels" . | nindent 4 }}
spec:
  hosts:
    - "{{ include "kube-code-server.fullname" . }}.{{ .Values.mainDomain }}"
  gateways:
    - 'istio-system/internal-gateway'
  http:
    - route:
        - destination:
            port:
              number: {{ .Values.service.port }}
            host: '{{ include "kube-code-server.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local'
